### ISSUE TITLE
"Fatal error: Maximum execution time" when a few "Display [provider] preferences" are enabled

### ISSUE THREAD

**Issue by maniqui** [NicolasGraph/oui_player#2]
I'm still tracking this down. I'm getting a:

```
Fatal error: Maximum execution time of 30 seconds exceeded in /home/sites/xxxxxxx/public/textpattern/lib/txplib_misc.php on line 1902
```

when I activate a few preferences (Soundcloud, Mixcloud, Vimeo, Youtube). I'm not sure if it's related to the amount of DB fields it has to fetch for the whole Preferences screen or if it's related to some of the oui_player preferences. I think it might be an issue with Soundcloud/Mixcloud preferences, although I've to prove that yet.

**Comment by maniqui** [comment]
It might be related. See on the screenshot below, how Soundcloud preferences are enabled and Mixcloud are disabled, but on the left tabs, the Mixcloud link is shown and the Soundcloud link is missing. 

![image](https://cloud.githubusercontent.com/assets/333695/23529471/874311d8-ff7c-11e6-8b17-0a27a5601ab5.png)

**Comment by NicolasGraph** [comment]
Thanks @maniqui for the report, I'll try to reproduce and fix it next week.

**Comment by NicolasGraph** [comment]
Inversed provider prefs are related the [en-gb textpack](https://github.com/NicolasGraph/oui_player/blob/dev/textpacks/en-gb.textpack); I [fixed it](https://github.com/NicolasGraph/oui_player/commit/dcae155857bb2da39c0645d6eb590b0a4e5009a9) in the dev branch; no big deal.

**Comment by NicolasGraph** [comment]
@maniqui, I think you are right about the amount of DB fields.
I'm not sure about the better way to avoid that. 

On my side I could:
- use a select list to display players prefs only one by one, but it wouldn't be ideal;
- code a extension tab to display the plugin related prefs only, but I need more time and a way to exclude these prefs from the regular preferences tab…

I'll investigate…

In the meanwhile, you can:
- [raise your time limit](https://textpattern.com/faq/261/fatal-error-maximum-execution-time);
- avoid to display too many players prefs at the same time (hidding them after customization before to display others).

**Comment by NicolasGraph** [comment]
@maniqui, I performed more tests and found an issue concerning the `prefWidget()`function used to automatically display the right widget for each plugin prefs according to valid values. It really slows the prefs display when too many of them are enable. I'm working on it.

**Comment by NicolasGraph** [comment]
https://github.com/NicolasGraph/oui_player/commit/1598f33417f2b38c60edb3a3bbfab0e2fff76655
