### ISSUE TITLE
Youtube URLs for playlists not working on v1.3.1 (worked on v1.2.1) 

### ISSUE THREAD

**Issue by maniqui** [NicolasGraph/oui_player#3]
On oui_player v1.2.1 I was able to pass it an URL for a YouTube playlist, like this one:

`https://www.youtube.com/watch?v=k3qgrSon4To&list=PLgkSUkbS9MLs9LSkGlRAJA-dbiaHpycqq`

and oui_player will do its magic and output the proper "player"  code (ie. the `iframe`).   

Now I've upgraded to v1.3.1 and the plugin isn't outputting any code at all.
I didn't have time to debug it properly (so I could get a quick patch to apply) but it seems it all boils down to this line. oui_player is not extracting the `id` properly.

`$id = preg_match('/([.][a-z]+\/)/', $this->play) ? $this->getInfos()['id'] : $this->play;]`

**Comment by NicolasGraph** [comment]
Thanks for the report @maniqui.
I'll take a look for the better solution but as for now changing the regular expression found [here](https://github.com/NicolasGraph/oui_player/blob/master/src/player/providers/Youtube.php#L27)
by `^(http|https):\/\/(www.)?(youtube\.com\/((watch\?v=)|(embed\/)|(v\/))|youtu\.be\/)([^\?\/]+)$` (removing `\&`) should help.

**Comment by NicolasGraph** [comment]
Sorry, I need to look deeper in the code and check Youtube players parameters. I'm not sure how lists should be managed. The code line you mentioned is ok, it just checks if there is a dot (`[a-z]`seems useless to me now) in the value provided via the `play` attribute to decide if it needs to parsed or not.
A part of the problem comes from [this line](https://github.com/NicolasGraph/oui_player/blob/master/src/player/providers/Youtube.php#L27). Did I change it? Not sure…

**Comment by NicolasGraph** [comment]
I just used your URL with v1.2.1 and it works but the player source is… 

```
//www.youtube-nocookie.com/embed/https://www.youtube.com/watch?v=k3qgrSon4To&list=PLgkSUkbS9MLs9LSkGlRAJA-dbiaHpycqq
```

It's was a bug; it should be…

```
https://www.youtube.com/embed/k3qgrSon4To?list=PLgkSUkbS9MLs9LSkGlRAJA-dbiaHpycqq
```

I need to add a way to play lists but I'm not sure URL's with `v`AND `list` will work as you expect. `list` could be an attribute like any other player parameters.

**Comment by NicolasGraph** [comment]
Ok, here is a quick patch I'll try to apply in a more generic way if it make sense.
Replace [this line](https://github.com/NicolasGraph/oui_player/blob/master/src/player/providers/Youtube.php#L27) and the following one by:

``` 
'scheme' => '#^(http|https):\/\/(www.)?(youtube\.com\/(watch\?v=|embed\/|v\/)|youtu\.be\/)(([^\&\?\/]+)((\&|\?)list=[^\&\?\/]+)?)#i',
'id'     => '5',
```

Then, add the following method before [this closing brace](https://github.com/NicolasGraph/oui_player/blob/master/src/player/providers/Youtube.php#L112):
```
/**
 * Get the item URL, provider and ID from the play property.
 */
public function getInfos()
{
    foreach ($this->patterns as $pattern => $options) {
        if (preg_match($options['scheme'], $this->play, $matches)) {
            $infos = array(
                'url'      => $this->play,
                'provider' => strtolower(substr(strrchr(get_class($this), '\\'), 1)),
                'type'     => $pattern,
                'id'       => str_replace(
                    htmlspecialchars_decode($this->glue[1]),
                    htmlspecialchars_decode($this->glue[0]),
                    $matches[$options['id']]
                ),
            );
            return $infos;
        }
    }

    return false;
}
```
Your URL should works now.

**Comment by maniqui** [comment]
> The code line you mentioned is ok, it just checks if there is a dot ([a-z]seems useless to me now) in the value provided via the play attribute to decide if it needs to parsed or not.

Yeah, I noticed (after posting this issue) that that line wasn't the issue, as it was only testing if it was a full 
URL and if so, running the getInfos to get the proper id.

Good news, your patch seems to work properly. Thanks! :+1:

**Comment by NicolasGraph** [comment]
> Good news, your patch seems to work properly.

Great, I'm working on the next version and it will be properly included.

**Comment by NicolasGraph** [comment]
Sorry for the delay; I finally released a v2, including this fix.
