### ISSUE TITLE
JS script for Vine is included even when not embedding Vine posts

### ISSUE THREAD

**Issue by maniqui** [NicolasGraph/oui_player#4]
I've noticed that just before the closing `</body>', the Vine script (`https://platform.vine.co/static/scripts/embed.js`) was being injected on every page I'm using oui_player, even if I'm not embedding Vine content.

To avoid this, I've changed the corresponding properties from `protected` to `private`, both in class `Provider` and on extending class `Vine`.

Not sure if this is the correct solution and if it will work when embedding Vine content, but at least for me, it stopped injecting the script.

**Comment by NicolasGraph** [comment]
Thanks for the report @maniqui, I already [fixed](https://github.com/NicolasGraph/oui_player/commit/2c45f68e34116fccaab3ebb7c4fb31393021bd46) this bug my way in the dev branch and will release it in few weeks I think.

**Comment by NicolasGraph** [comment]
Sorry for the delay; I finally released a v2, including this fix.
